# Generated by Django 5.0 on 2023-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_date',
            field=models.DateField(),
        ),
    ]
